### ISSUE TITLE
The Angular module and controller

### ISSUE THREAD

**Issue by ameliaburger** [cpolyukh/coordination#4]

**Comment by cpolyukh** [comment]
Just finished setting up the module and controller. Basically what's left to do is the validation of the fields in the form (aside from simply checking if required fields are present which has already been implemented) and a confirmation message when the form is successfully submitted. We don't have to store or send the entered data which is nice and will save us time.

I'm about to create some tests to ensure that everything is functioning correctly when fields are left empty since I think that's all I can really check for right now. I'll update you once I push that.

**Comment by cpolyukh** [comment]
Okay so I went ahead and merged what I have so far since it's at a point where you can continue on and all I have to add are a few tests. I have the basic structure of the test files set up and will get my testing code in tomorrow afternoon.
